### ISSUE TITLE
Hello, can you provide the train_config file?

### ISSUE THREAD

**Issue by chenxiao521** [xiyang1012/Local-Crowd-Counting#2]

**Comment by LoryMANG** [comment]
Same file missing.

**Comment by xiyang1012** [comment]
Thanks for comments. We have no plans to release the training code recently. You can try it according to the details of the paper.

**Comment by LoryMANG** [comment]
> Thanks for comments. We have no plans to release the training code recently. You can try it according to the details of the paper.

Ok,So how can i test with the pretrained model without training?How to config the test_config.py file?Can u give some tips?Thank you very much.

**Comment by xiyang1012** [comment]
Here are some mistakes and we have fixed them. Use the latest code please.

**Comment by xiyang1012** [comment]
Here are some mistakes and we have fixed them. Use the latest code please.
You only need to set MODEL_PATH to your model path in test_config.py.

**Comment by xuweitj** [comment]
useless!ImportError: No module named 'train_config'. I git the latest code.But I still have the same mistakes!

**Comment by LoryMANG** [comment]
> Here are some mistakes and we have fixed them. Use the latest code please.
> You only need to set MODEL_PATH to your model path in test_config.py.

I have git the latest code,Same problem,it need the train_config.py file.

**Comment by xiyang1012** [comment]
Sorry for that, we have updated the code again.

**Comment by LoryMANG** [comment]
> Sorry for that, we have updated the code again.

Thank you very much! It works now.

**Comment by xuweitj** [comment]
> Sorry for that, we have updated the code again.

Thank you very much!
